#!/bin/sh
set -eu

/usr/local/bin/symba-assert-postgres-contract

# The bootstrap superuser is a local break-glass identity only. Keep Unix
# socket peer administration available to the container's postgres OS user,
# but reject every TCP connection for the database role before the generic
# SCRAM host rule generated by the official image. The hardener validates the
# exact initdb/auth contract and atomically replaces pg_hba.conf on its own
# filesystem so a failed render cannot leave a partial policy.
/usr/local/bin/symba-harden-pg-hba

# Fixed identifiers are deliberate. Passwords are read by psql from the
# environment rather than interpolated by the shell or exposed in argv.
psql --username "$POSTGRES_USER" --dbname postgres --set=ON_ERROR_STOP=1 <<'EOSQL'
\getenv migration_password SYMBA_POSTGRES_MIGRATION_PASSWORD
\getenv runtime_password SYMBA_POSTGRES_RUNTIME_PASSWORD

SELECT format(
    'CREATE ROLE symba_migrator LOGIN PASSWORD %L NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS',
    :'migration_password'
)
WHERE NOT EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = 'symba_migrator')
\gexec
SELECT format(
    'ALTER ROLE symba_migrator WITH LOGIN PASSWORD %L NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS',
    :'migration_password'
)
\gexec

SELECT format(
    'CREATE ROLE symba_runtime LOGIN PASSWORD %L NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS',
    :'runtime_password'
)
WHERE NOT EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = 'symba_runtime')
\gexec
SELECT format(
    'ALTER ROLE symba_runtime WITH LOGIN PASSWORD %L NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS',
    :'runtime_password'
)
\gexec

SELECT 'CREATE DATABASE symba OWNER symba_migrator'
WHERE NOT EXISTS (SELECT 1 FROM pg_catalog.pg_database WHERE datname = 'symba')
\gexec

REVOKE CONNECT, TEMPORARY ON DATABASE postgres FROM PUBLIC;
REVOKE CONNECT, TEMPORARY ON DATABASE template1 FROM PUBLIC;
REVOKE ALL ON DATABASE symba FROM PUBLIC;
GRANT CONNECT ON DATABASE symba TO symba_migrator, symba_runtime;

\connect symba
REVOKE ALL ON SCHEMA public FROM PUBLIC;
CREATE SCHEMA IF NOT EXISTS symba AUTHORIZATION symba_migrator;
ALTER SCHEMA symba OWNER TO symba_migrator;
GRANT USAGE ON SCHEMA symba TO symba_runtime;

ALTER DEFAULT PRIVILEGES FOR ROLE symba_migrator IN SCHEMA symba
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO symba_runtime;
ALTER DEFAULT PRIVILEGES FOR ROLE symba_migrator IN SCHEMA symba
    GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO symba_runtime;

-- PostgreSQL grants function EXECUTE and type USAGE to PUBLIC by default.
-- Revoke those global owner defaults before granting only the runtime role in
-- the application schema.
ALTER DEFAULT PRIVILEGES FOR ROLE symba_migrator
    REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE symba_migrator IN SCHEMA symba
    GRANT EXECUTE ON FUNCTIONS TO symba_runtime;
ALTER DEFAULT PRIVILEGES FOR ROLE symba_migrator
    REVOKE USAGE ON TYPES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE symba_migrator IN SCHEMA symba
    GRANT USAGE ON TYPES TO symba_runtime;

ALTER ROLE symba_migrator IN DATABASE symba SET search_path = symba, public;
ALTER ROLE symba_runtime IN DATABASE symba SET search_path = symba, public;
EOSQL
